--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: cloud-config-server-app
  name: cloud-config-server-app
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: cloud-config-server-app
  template: 
    metadata: 
      labels: 
        app: cloud-config-server-app
    spec: 
      containers: 
        - 
          image: "pnvyas1327/cloud-config-server:0.0.1"
          imagePullPolicy: Always
          name: cloud-config-server-app
          ports: 
            - 
              containerPort: 9296


--- 
apiVersion: v1
kind: Service
metadata: 
  name: cloud-config-server-svc
spec: 
  ports: 
    - 
      port: 80
      targetPort: 9296
  selector: 
    app: cloud-config-server-svc
  type: ClusterIP
