--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: user-service-app
  name: user-service-app
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: user-service-app
  template: 
    metadata: 
      labels: 
        app: user-service-app
    spec: 
      containers: 
        - 
          image: "pnvyas1327/user-service:0.0.1"
          imagePullPolicy: Always
          name: user-service-app
          ports: 
            - 
              containerPort: 9002
              
--- 
apiVersion: v1
kind: Service
metadata: 
  name: user-service-svc
spec: 
  ports: 
    - 
      port: 80
      targetPort: 9002
  selector: 
    app: user-service-svc
  type: ClusterIP
