server:
  port: 8081

#spring.main.web-application-type=NONE 
  # REACTIVE, SERVLET
spring:
  application:
    name: API-GATEWAY
  main:
    web-application-type: REACTIVE     
  cloud:
    gateway:
      discovery:
        locator:          enabled: true          lower-case-service-id: true
      routes:      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:          - Path=/users/**
        filters:
          - name: CircuitBreaker
            args:
              name: USER-SERVICE
              fallbackuri: forward:/userServiceFallBack 
      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
          - Path=/departments/**
        filters:
          - name: CircuitBreaker
            args:
              name: DEPARTMENT-SERVICE
              fallbackuri: forward:/departmentServiceFallBack


hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000  
            
            
management:
  endpoints:
     web:
      exposure:
        include: hystrix.stream    
